#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use feature ':5.10';

# CPAN MODULE:
use Mojolicious::Lite;

# Static file path:
unshift @{app->static->paths}, $ENV{PWD};

# ROUTE HANDLER:
get '/' => sub {
  my $page_handler = shift;
  $page_handler->reply->static('magna-carta.html');
};

# SERVER STARTER:
app->start;
